/**
 * This file is generated by tifstoc. Do not edit!
 * Generated from tifs for tool 'sglr' (prefix='')
 */

#ifndef _SGLR_H
#define _SGLR_H

#include <atb-tool.h>

/* Prototypes for functions called from the event handler */
void rec_terminate(int conn, ATerm);
ATerm parse(int conn, const char *, ATerm, const char *, ATerm);
ATerm sglr_handler(int conn, ATerm term);
ATerm sglr_checker(int conn, ATerm sigs);

#endif
